<?php
/**
 * List of templates
 *
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit; // Exit if accessed directly.
}

if ( ! function_exists( 'wpkoi_templates_for_elementor_template_list' ) ) {
	function wpkoi_templates_for_elementor_template_list() {
		$templates = array (
			0 => array (
			  'template_id' => 5500,
			  'thumbnail' => 'bekko-home-thumb.jpg',
			  'title' => 'Bekko Home',
			  'url' => 'https://wpkoi.com/wpkoi-elementor-templates-demo/bekko-home/',
			),
			1 => array (
			  'template_id' => 5501,
			  'thumbnail' => 'bekko-about-us-thumb.jpg',
			  'title' => 'Bekko About Us',
			  'url' => 'https://wpkoi.com/wpkoi-elementor-templates-demo/bekko-about-us/',
			),
			2 => array (
			  'template_id' => 5502,
			  'thumbnail' => 'bekko-contact-thumb.jpg',
			  'title' => 'Bekko Contact',
			  'url' => 'https://wpkoi.com/wpkoi-elementor-templates-demo/bekko-contact/',
			),
			3 => array (
			  'template_id' => 5503,
			  'thumbnail' => 'chagoi-home-thumb.jpg',
			  'title' => 'Chagoi Home',
			  'url' => 'https://wpkoi.com/wpkoi-elementor-templates-demo/chagoi-home/',
			),
			4 => array (
			  'template_id' => 5504,
			  'thumbnail' => 'chagoi-about-us-thumb.jpg',
			  'title' => 'Chagoi About Us',
			  'url' => 'https://wpkoi.com/wpkoi-elementor-templates-demo/chagoi-about-us/',
			),
			5 => array (
			  'template_id' => 5505,
			  'thumbnail' => 'chagoi-contact-thumb.jpg',
			  'title' => 'Chagoi Contact',
			  'url' => 'https://wpkoi.com/wpkoi-elementor-templates-demo/chagoi-contact/',
			),
			6 => array (
			  'template_id' => 5506,
			  'thumbnail' => 'koromo-home-thumb.jpg',
			  'title' => 'Koromo Home',
			  'url' => 'https://wpkoi.com/wpkoi-elementor-templates-demo/koromo-home/',
			),
			7 => array (
			  'template_id' => 5507,
			  'thumbnail' => 'koromo-about-us-thumb.jpg',
			  'title' => 'Koromo About Us',
			  'url' => 'https://wpkoi.com/wpkoi-elementor-templates-demo/koromo-about-us/',
			),
			8 => array (
			  'template_id' => 5508,
			  'thumbnail' => 'koromo-contact-thumb.jpg',
			  'title' => 'Koromo Contact',
			  'url' => 'https://wpkoi.com/wpkoi-elementor-templates-demo/koromo-contact/',
			),
			9 => array (
			  'template_id' => 5509,
			  'thumbnail' => 'lovewp-home-thumb.jpg',
			  'title' => 'LoveWP Home',
			  'url' => 'https://wpkoi.com/wpkoi-elementor-templates-demo/lovewp-home/',
			),
			10 => array (
			  'template_id' => 5510,
			  'thumbnail' => 'lovewp-about-us-thumb.jpg',
			  'title' => 'LoveWP About Us',
			  'url' => 'https://wpkoi.com/wpkoi-elementor-templates-demo/lovewp-about-us/',
			),
			11 => array (
			  'template_id' => 5511,
			  'thumbnail' => 'lovewp-contact-thumb.jpg',
			  'title' => 'LoveWP Contact',
			  'url' => 'https://wpkoi.com/wpkoi-elementor-templates-demo/lovewp-contact/',
			),
			12 => array (
			  'template_id' => 5512,
			  'thumbnail' => 'goshiki-home-thumb.jpg',
			  'title' => 'Goshiki Home',
			  'url' => 'https://wpkoi.com/wpkoi-elementor-templates-demo/goshiki-home/',
			),
			13 => array (
			  'template_id' => 5513,
			  'thumbnail' => 'goshiki-about-us-thumb.jpg',
			  'title' => 'Goshiki About Us',
			  'url' => 'https://wpkoi.com/wpkoi-elementor-templates-demo/goshiki-about-us/',
			),
			14 => array (
			  'template_id' => 5514,
			  'thumbnail' => 'goshiki-contact-thumb.jpg',
			  'title' => 'Goshiki Contact',
			  'url' => 'https://wpkoi.com/wpkoi-elementor-templates-demo/goshiki-contact/',
			),
			15 => array (
			  'template_id' => 5515,
			  'thumbnail' => 'kinginrin-home-thumb.jpg',
			  'title' => 'Kinginrin Home',
			  'url' => 'https://wpkoi.com/wpkoi-elementor-templates-demo/kinginrin-home/',
			),
			16 => array (
			  'template_id' => 5516,
			  'thumbnail' => 'kinginrin-about-us-thumb.jpg',
			  'title' => 'Kinginrin About Us',
			  'url' => 'https://wpkoi.com/wpkoi-elementor-templates-demo/kinginrin-about-us/',
			),
			17 => array (
			  'template_id' => 5517,
			  'thumbnail' => 'kinginrin-contact-thumb.jpg',
			  'title' => 'Kinginrin Contact',
			  'url' => 'https://wpkoi.com/wpkoi-elementor-templates-demo/kinginrin-contact/',
			),
			18 => array (
			  'template_id' => 5518,
			  'thumbnail' => 'kohaku-home-thumb.jpg',
			  'title' => 'Kohaku Home',
			  'url' => 'https://wpkoi.com/wpkoi-elementor-templates-demo/kohaku-home/',
			),
			19 => array (
			  'template_id' => 5519,
			  'thumbnail' => 'kohaku-about-us-thumb.jpg',
			  'title' => 'Kohaku About Us',
			  'url' => 'https://wpkoi.com/wpkoi-elementor-templates-demo/kohaku-about-us/',
			),
			20 => array (
			  'template_id' => 5520,
			  'thumbnail' => 'kohaku-contact-thumb.jpg',
			  'title' => 'Kohaku Contact',
			  'url' => 'https://wpkoi.com/wpkoi-elementor-templates-demo/kohaku-contact/',
			),
			21 => array (
			  'template_id' => 5521,
			  'thumbnail' => 'ochiba-home-thumb.jpg',
			  'title' => 'Ochiba Home',
			  'url' => 'https://wpkoi.com/wpkoi-elementor-templates-demo/ochiba-home/',
			),
			22 => array (
			  'template_id' => 5522,
			  'thumbnail' => 'ochiba-about-us-thumb.jpg',
			  'title' => 'Ochiba About Us',
			  'url' => 'https://wpkoi.com/wpkoi-elementor-templates-demo/ochiba-about-us/',
			),
			23 => array (
			  'template_id' => 5523,
			  'thumbnail' => 'ochiba-contact-thumb.jpg',
			  'title' => 'Ochiba Contact',
			  'url' => 'https://wpkoi.com/wpkoi-elementor-templates-demo/ochiba-contact/',
			),
			24 => array (
			  'template_id' => 5524,
			  'thumbnail' => 'saraswati-home-thumb.jpg',
			  'title' => 'Saraswati Home',
			  'url' => 'https://wpkoi.com/wpkoi-elementor-templates-demo/saraswati-home/',
			),
			25 => array (
			  'template_id' => 5525,
			  'thumbnail' => 'saraswati-about-us-thumb.jpg',
			  'title' => 'Saraswati About Us',
			  'url' => 'https://wpkoi.com/wpkoi-elementor-templates-demo/saraswati-about-us/',
			),
			26 => array (
			  'template_id' => 5526,
			  'thumbnail' => 'saraswati-contact-thumb.jpg',
			  'title' => 'Saraswati Contact',
			  'url' => 'https://wpkoi.com/wpkoi-elementor-templates-demo/saraswati-contact/',
			),
			27 => array (
			  'template_id' => 5527,
			  'thumbnail' => 'tancho-home-thumb.jpg',
			  'title' => 'Tancho Home',
			  'url' => 'https://wpkoi.com/wpkoi-elementor-templates-demo/tancho-home/',
			),
			28 => array (
			  'template_id' => 5528,
			  'thumbnail' => 'tancho-about-us-thumb.jpg',
			  'title' => 'Tancho About Us',
			  'url' => 'https://wpkoi.com/wpkoi-elementor-templates-demo/tancho-about-us/',
			),
			29 => array (
			  'template_id' => 5529,
			  'thumbnail' => 'tancho-contact-thumb.jpg',
			  'title' => 'Tancho Contact',
			  'url' => 'https://wpkoi.com/wpkoi-elementor-templates-demo/tancho-contact/',
			),
			30 => array (
			  'template_id' => 5530,
			  'thumbnail' => 'asagi-home-thumb.jpg',
			  'title' => 'Asagi Home',
			  'url' => 'https://wpkoi.com/wpkoi-elementor-templates-demo/asagi-home/',
			),
			31 => array (
			  'template_id' => 5531,
			  'thumbnail' => 'asagi-about-us-thumb.jpg',
			  'title' => 'Asagi About Us',
			  'url' => 'https://wpkoi.com/wpkoi-elementor-templates-demo/asagi-about-us/',
			),
			32 => array (
			  'template_id' => 5532,
			  'thumbnail' => 'asagi-contact-thumb.jpg',
			  'title' => 'Asagi Contact',
			  'url' => 'https://wpkoi.com/wpkoi-elementor-templates-demo/asagi-contact/',
			),
			33 => array (
			  'template_id' => 5533,
			  'thumbnail' => 'narayana-home-thumb.jpg',
			  'title' => 'Narayana Home',
			  'url' => 'https://wpkoi.com/wpkoi-elementor-templates-demo/narayana-home/',
			),
			34 => array (
			  'template_id' => 5534,
			  'thumbnail' => 'narayana-about-us-thumb.jpg',
			  'title' => 'Narayana About Us',
			  'url' => 'https://wpkoi.com/wpkoi-elementor-templates-demo/narayana-about-us/',
			),
			35 => array (
			  'template_id' => 5535,
			  'thumbnail' => 'narayana-contact-thumb.jpg',
			  'title' => 'Narayana Contact',
			  'url' => 'https://wpkoi.com/wpkoi-elementor-templates-demo/narayana-contact/',
			),
			36 => array (
			  'template_id' => 5536,
			  'thumbnail' => 'nataraja-home-thumb.jpg',
			  'title' => 'Nataraja Home',
			  'url' => 'https://wpkoi.com/wpkoi-elementor-templates-demo/nataraja-home/',
			),
			37 => array (
			  'template_id' => 5537,
			  'thumbnail' => 'nataraja-about-us-thumb.jpg',
			  'title' => 'Nataraja About Us',
			  'url' => 'https://wpkoi.com/wpkoi-elementor-templates-demo/nataraja-about-us/',
			),
			38 => array (
			  'template_id' => 5538,
			  'thumbnail' => 'nataraja-contact-thumb.jpg',
			  'title' => 'Nataraja Contact',
			  'url' => 'https://wpkoi.com/wpkoi-elementor-templates-demo/nataraja-contact/',
			),
			39 => array (
			  'template_id' => 5539,
			  'thumbnail' => 'rudra-home-thumb.jpg',
			  'title' => 'Rudra Home',
			  'url' => 'https://wpkoi.com/wpkoi-elementor-templates-demo/rudra-home/',
			),
			40 => array (
			  'template_id' => 5540,
			  'thumbnail' => 'rudra-about-us-thumb.jpg',
			  'title' => 'Rudra About Us',
			  'url' => 'https://wpkoi.com/wpkoi-elementor-templates-demo/rudra-about-us/',
			),
			41 => array (
			  'template_id' => 5541,
			  'thumbnail' => 'rudra-contact-thumb.jpg',
			  'title' => 'Rudra Contact',
			  'url' => 'https://wpkoi.com/wpkoi-elementor-templates-demo/rudra-contact/',
			),
			42 => array (
			  'template_id' => 5542,
			  'thumbnail' => 'valmiki-free-thumb.jpg',
			  'title' => 'Valmiki Free',
			  'url' => 'https://wpkoi.com/wpkoi-elementor-templates-demo/valmiki-free/',
			),
			43 => array (
			  'template_id' => 5543,
			  'thumbnail' => 'ganga-free-thumb.jpg',
			  'title' => 'Ganga Free',
			  'url' => 'https://wpkoi.com/wpkoi-elementor-templates-demo/ganga-free/',
			),
			44 => array (
			  'template_id' => 5544,
			  'thumbnail' => 'durga-free-thumb.jpg',
			  'title' => 'Durga Free',
			  'url' => 'https://wpkoi.com/wpkoi-elementor-templates-demo/durga-free/',
			),
			45 => array (
			  'template_id' => 5545,
			  'thumbnail' => 'mohini-free-thumb.jpg',
			  'title' => 'Mohini Free',
			  'url' => 'https://wpkoi.com/wpkoi-elementor-templates-demo/mohini-free/',
			),
			46 => array (
			  'template_id' => 5546,
			  'thumbnail' => 'tulsi-free-thumb.jpg',
			  'title' => 'Tulsi Free',
			  'url' => 'https://wpkoi.com/wpkoi-elementor-templates-demo/tulsi-free/',
			),
			47 => array (
			  'template_id' => 5547,
			  'thumbnail' => 'kurma-free-thumb.jpg',
			  'title' => 'Kurma Free',
			  'url' => 'https://wpkoi.com/wpkoi-elementor-templates-demo/kurma-free/',
			),
			48 => array (
			  'template_id' => 5548,
			  'thumbnail' => 'parvati-free-thumb.jpg',
			  'title' => 'Parvati Free',
			  'url' => 'https://wpkoi.com/wpkoi-elementor-templates-demo/parvati-free/',
			),
			49 => array (
			  'template_id' => 5549,
			  'thumbnail' => 'shesha-free-thumb.jpg',
			  'title' => 'Shesha Free',
			  'url' => 'https://wpkoi.com/wpkoi-elementor-templates-demo/shesha-free/',
			),
			50 => array (
			  'template_id' => 5550,
			  'thumbnail' => 'lingam-free-thumb.jpg',
			  'title' => 'Lingam Free',
			  'url' => 'https://wpkoi.com/wpkoi-elementor-templates-demo/lingam-free/',
			),
			51 => array (
			  'template_id' => 5551,
			  'thumbnail' => 'nandi-free-thumb.jpg',
			  'title' => 'Nandi Free',
			  'url' => 'https://wpkoi.com/wpkoi-elementor-templates-demo/nandi-free/',
			),
			52 => array (
			  'template_id' => 5552,
			  'thumbnail' => 'vishnu-free-thumb.jpg',
			  'title' => 'Vishnu Free',
			  'url' => 'https://wpkoi.com/wpkoi-elementor-templates-demo/vishnu-free/',
			),
			53 => array (
			  'template_id' => 5553,
			  'thumbnail' => 'gayatri-free-thumb.jpg',
			  'title' => 'Gayatri Free',
			  'url' => 'https://wpkoi.com/wpkoi-elementor-templates-demo/gayatri-free/',
			),
			54 => array (
			  'template_id' => 5554,
			  'thumbnail' => 'chandi-free-thumb.jpg',
			  'title' => 'Chandi Free',
			  'url' => 'https://wpkoi.com/wpkoi-elementor-templates-demo/chandi-free/',
			),
			55 => array (
			  'template_id' => 5555,
			  'thumbnail' => 'indra-free-thumb.jpg',
			  'title' => 'Indra Free',
			  'url' => 'https://wpkoi.com/wpkoi-elementor-templates-demo/indra-free/',
			),
			56 => array (
			  'template_id' => 5556,
			  'thumbnail' => 'asura-free-thumb.jpg',
			  'title' => 'Asura Free',
			  'url' => 'https://wpkoi.com/wpkoi-elementor-templates-demo/asura-free/',
			),
			57 => array (
			  'template_id' => 5557,
			  'thumbnail' => 'kubera-free-thumb.jpg',
			  'title' => 'Kubera Free',
			  'url' => 'https://wpkoi.com/wpkoi-elementor-templates-demo/kubera-free/',
			),
			58 => array (
			  'template_id' => 5558,
			  'thumbnail' => 'jumadi-free-thumb.jpg',
			  'title' => 'Jumadi Free',
			  'url' => 'https://wpkoi.com/wpkoi-elementor-templates-demo/jumadi-free/',
			),
			59 => array (
			  'template_id' => 5559,
			  'thumbnail' => 'kalki-free-thumb.jpg',
			  'title' => 'Kalki Free',
			  'url' => 'https://wpkoi.com/wpkoi-elementor-templates-demo/kalki-free/',
			),
			60 => array (
			  'template_id' => 5560,
			  'thumbnail' => 'dhara-free-thumb.jpg',
			  'title' => 'Dhara Free',
			  'url' => 'https://wpkoi.com/wpkoi-elementor-templates-demo/dhara-free/',
			),
			61 => array (
			  'template_id' => 5561,
			  'thumbnail' => 'yamuna-free-thumb.jpg',
			  'title' => 'Yamuna Free',
			  'url' => 'https://wpkoi.com/wpkoi-elementor-templates-demo/yamuna-free/',
			),
			62 => array (
			  'template_id' => 5562,
			  'thumbnail' => 'garuda-free-thumb.jpg',
			  'title' => 'Garuda Free',
			  'url' => 'https://wpkoi.com/wpkoi-elementor-templates-demo/garuda-free/',
			),
			63 => array (
			  'template_id' => 5563,
			  'thumbnail' => 'aravan-free-thumb.jpg',
			  'title' => 'Aravan Free',
			  'url' => 'https://wpkoi.com/wpkoi-elementor-templates-demo/aravan-free/',
			),
			64 => array (
			  'template_id' => 5564,
			  'thumbnail' => 'bhaga-free-thumb.jpg',
			  'title' => 'Bhaga Free',
			  'url' => 'https://wpkoi.com/wpkoi-elementor-templates-demo/bhaga-free/',
			),
			65 => array (
			  'template_id' => 5565,
			  'thumbnail' => 'matangi-free-thumb.jpg',
			  'title' => 'Matangi Free',
			  'url' => 'https://wpkoi.com/wpkoi-elementor-templates-demo/matangi-free/',
			),
			66 => array (
			  'template_id' => 5566,
			  'thumbnail' => 'ambika-free-thumb.jpg',
			  'title' => 'Ambika Free',
			  'url' => 'https://wpkoi.com/wpkoi-elementor-templates-demo/ambika-free/',
			),
			67 => array (
			  'template_id' => 5567,
			  'thumbnail' => 'sukra-free-thumb.jpg',
			  'title' => 'Sukra Free',
			  'url' => 'https://wpkoi.com/wpkoi-elementor-templates-demo/sukra-free/',
			),
			68 => array (
			  'template_id' => 5568,
			  'thumbnail' => 'mhalsa-free-thumb.jpg',
			  'title' => 'Mhalsa Free',
			  'url' => 'https://wpkoi.com/wpkoi-elementor-templates-demo/mhalsa-free/',
			),
			69 => array (
			  'template_id' => 5569,
			  'thumbnail' => 'vikata-free-thumb.jpg',
			  'title' => 'Vikata Free',
			  'url' => 'https://wpkoi.com/wpkoi-elementor-templates-demo/vikata-free/',
			),
			70 => array (
			  'template_id' => 5570,
			  'thumbnail' => 'karna-free-thumb.jpg',
			  'title' => 'Karna Free',
			  'url' => 'https://wpkoi.com/wpkoi-elementor-templates-demo/karna-free/',
			),
			71 => array (
			  'template_id' => 5571,
			  'thumbnail' => 'manda-free-thumb.jpg',
			  'title' => 'Manda Free',
			  'url' => 'https://wpkoi.com/wpkoi-elementor-templates-demo/manda-free/',
			),
			72 => array (
			  'template_id' => 5572,
			  'thumbnail' => 'lalita-free-thumb.jpg',
			  'title' => 'Lalita Free',
			  'url' => 'https://wpkoi.com/wpkoi-elementor-templates-demo/lalita-free/',
			),
			73 => array (
			  'template_id' => 5573,
			  'thumbnail' => 'mallanna-free-thumb.jpg',
			  'title' => 'Mallanna Free',
			  'url' => 'https://wpkoi.com/wpkoi-elementor-templates-demo/mallanna-free/',
			),
			74 => array (
			  'template_id' => 5575,
			  'thumbnail' => 'samudra-free-thumb.jpg',
			  'title' => 'Samudra Free',
			  'url' => 'https://wpkoi.com/wpkoi-elementor-templates-demo/samudra-free/',
			),
			75 => array (
			  'template_id' => 5576,
			  'thumbnail' => 'varuna-free-thumb.jpg',
			  'title' => 'Varuna Free',
			  'url' => 'https://wpkoi.com/wpkoi-elementor-templates-demo/varuna-free/',
			),
			76 => array (
			  'template_id' => 5577,
			  'thumbnail' => 'manasa-free-thumb.jpg',
			  'title' => 'Manasa Free',
			  'url' => 'https://wpkoi.com/wpkoi-elementor-templates-demo/manasa-free/',
			),
			77 => array (
			  'template_id' => 5578,
			  'thumbnail' => 'narmada-free-thumb.jpg',
			  'title' => 'Narmada Free',
			  'url' => 'https://wpkoi.com/wpkoi-elementor-templates-demo/narmada-free/',
			),
			78 => array (
			  'template_id' => 5579,
			  'thumbnail' => 'pushan-free-thumb.jpg',
			  'title' => 'Pushan Free',
			  'url' => 'https://wpkoi.com/wpkoi-elementor-templates-demo/pushan-free/',
			),
			79 => array (
			  'template_id' => 5580,
			  'thumbnail' => 'aditi-free-thumb.jpg',
			  'title' => 'Aditi Free',
			  'url' => 'https://wpkoi.com/wpkoi-elementor-templates-demo/aditi-free/',
			),
			80 => array (
			  'template_id' => 5581,
			  'thumbnail' => 'skanda-free-thumb.jpg',
			  'title' => 'Skanda Free',
			  'url' => 'https://wpkoi.com/wpkoi-elementor-templates-demo/skanda-free/',
			),
			81 => array (
			  'template_id' => 5582,
			  'thumbnail' => 'moksa-free-thumb.jpg',
			  'title' => 'Moksa Free',
			  'url' => 'https://wpkoi.com/wpkoi-elementor-templates-demo/moksa-free/',
			),
			82 => array (
			  'template_id' => 5583,
			  'thumbnail' => 'dhyana-free-thumb.jpg',
			  'title' => 'Dhyana Free',
			  'url' => 'https://wpkoi.com/wpkoi-elementor-templates-demo/dhyana-free/',
			),
			83 => array (
			  'template_id' => 5584,
			  'thumbnail' => 'kalaratri-free-thumb.jpg',
			  'title' => 'Kalaratri Free',
			  'url' => 'https://wpkoi.com/wpkoi-elementor-templates-demo/kalaratri-free/',
			),
			84 => array (
			  'template_id' => 5585,
			  'thumbnail' => 'durvasa-free-thumb.jpg',
			  'title' => 'Durvasa Free',
			  'url' => 'https://wpkoi.com/wpkoi-elementor-templates-demo/durvasa-free/',
			),
			85 => array (
			  'template_id' => 5586,
			  'thumbnail' => 'kalidasa-free-thumb.jpg',
			  'title' => 'Kalidasa Free',
			  'url' => 'https://wpkoi.com/wpkoi-elementor-templates-demo/kalidasa-free/',
			),
			86 => array (
			  'template_id' => 5587,
			  'thumbnail' => 'vajra-free-thumb.jpg',
			  'title' => 'Vajra Free',
			  'url' => 'https://wpkoi.com/wpkoi-elementor-templates-demo/vajra-free/',
			),
			87 => array (
			  'template_id' => 5588,
			  'thumbnail' => 'purusha-free-thumb.jpg',
			  'title' => 'Purusha Free',
			  'url' => 'https://wpkoi.com/wpkoi-elementor-templates-demo/purusha-free/',
			),
			88 => array (
			  'template_id' => 5589,
			  'thumbnail' => 'ashram-free-thumb.jpg',
			  'title' => 'Ashram Free',
			  'url' => 'https://wpkoi.com/wpkoi-elementor-templates-demo/ashram-free/',
			),
			89 => array (
			  'template_id' => 5590,
			  'thumbnail' => 'ishvara-free-thumb.jpg',
			  'title' => 'Ishvara Free',
			  'url' => 'https://wpkoi.com/wpkoi-elementor-templates-demo/ishvara-free/',
			),
			90 => array (
			  'template_id' => 5591,
			  'thumbnail' => 'shudra-free-thumb.jpg',
			  'title' => 'Shudra Free',
			  'url' => 'https://wpkoi.com/wpkoi-elementor-templates-demo/shudra-free/',
			),
			91 => array (
			  'template_id' => 5592,
			  'thumbnail' => 'agni-free-thumb.jpg',
			  'title' => 'Agni Free',
			  'url' => 'https://wpkoi.com/wpkoi-elementor-templates-demo/agni-free/',
			),
			92 => array (
			  'template_id' => 5593,
			  'thumbnail' => 'sukha-free-thumb.jpg',
			  'title' => 'Sukha Free',
			  'url' => 'https://wpkoi.com/wpkoi-elementor-templates-demo/sukha-free/',
			),
			93 => array (
			  'template_id' => 5594,
			  'thumbnail' => 'havan-free-thumb.jpg',
			  'title' => 'Havan Free',
			  'url' => 'https://wpkoi.com/wpkoi-elementor-templates-demo/havan-free/',
			),
			94 => array (
			  'template_id' => 5595,
			  'thumbnail' => 'madhura-free-thumb.jpg',
			  'title' => 'Madhura Free',
			  'url' => 'https://wpkoi.com/wpkoi-elementor-templates-demo/madhura-free/',
			),
			95 => array (
			  'template_id' => 5596,
			  'thumbnail' => 'ishta-free-thumb.jpg',
			  'title' => 'Ishta Free',
			  'url' => 'https://wpkoi.com/wpkoi-elementor-templates-demo/ishta-free/',
			),
			96 => array (
			  'template_id' => 'omkara-free',
			  'thumbnail' => 'omkara-free-thumb.jpg',
			  'title' => 'Omkara Free',
			  'url' => 'https://wpkoi.com/wpkoi-elementor-templates-demo/omkara-free/',
			),
			97 => array (
			  'template_id' => 'sakti-free',
			  'thumbnail' => 'sakti-free-thumb.jpg',
			  'title' => 'Sakti Free',
			  'url' => 'https://wpkoi.com/wpkoi-elementor-templates-demo/sakti-free/',
			),
			98 => array (
			  'template_id' => 'mahatma-free',
			  'thumbnail' => 'mahatma-free-thumb.jpg',
			  'title' => 'Mahatma Free',
			  'url' => 'https://wpkoi.com/wpkoi-elementor-templates-demo/mahatma-free/',
			),
			99 => array (
			  'template_id' => 'daksha-free',
			  'thumbnail' => 'daksha-free-thumb.jpg',
			  'title' => 'Daksha Free',
			  'url' => 'https://wpkoi.com/wpkoi-elementor-templates-demo/daksha-free/',
			),
			100 => array (
			  'template_id' => 'neela-free',
			  'thumbnail' => 'neela-free-thumb.jpg',
			  'title' => 'Neela Free',
			  'url' => 'https://wpkoi.com/wpkoi-elementor-templates-demo/neela-free/',
			),
			101 => array (
			  'template_id' => 'daiva-free',
			  'thumbnail' => 'daiva-free-thumb.jpg',
			  'title' => 'Daiva Free',
			  'url' => 'https://wpkoi.com/wpkoi-elementor-templates-demo/daiva-free/',
			),
			102 => array (
			  'template_id' => 'pandita-free',
			  'thumbnail' => 'pandita-free-thumb.jpg',
			  'title' => 'Pandita Free',
			  'url' => 'https://wpkoi.com/wpkoi-elementor-templates-demo/pandita-free/',
			),
			103 => array (
			  'template_id' => 'samana-free',
			  'thumbnail' => 'samana-free-thumb.jpg',
			  'title' => 'Samana Free',
			  'url' => 'https://wpkoi.com/wpkoi-elementor-templates-demo/samana-free/',
			),
			104 => array (
			  'template_id' => 'adarsa-free',
			  'thumbnail' => 'adarsa-free-thumb.jpg',
			  'title' => 'Adarsa Free',
			  'url' => 'https://wpkoi.com/wpkoi-elementor-templates-demo/adarsa-free/',
			),
			105 => array (
			  'template_id' => 'itara-free',
			  'thumbnail' => 'itara-free-thumb.jpg',
			  'title' => 'Itara Free',
			  'url' => 'https://wpkoi.com/wpkoi-elementor-templates-demo/itara-free/',
			),
			106 => array (
			  'template_id' => 'nidra-free',
			  'thumbnail' => 'nidra-free-thumb.jpg',
			  'title' => 'Nidra Free',
			  'url' => 'https://wpkoi.com/wpkoi-elementor-templates-demo/nidra-free/',
			),
			107 => array (
			  'template_id' => 'sundara-free',
			  'thumbnail' => 'sundara-free-thumb.jpg',
			  'title' => 'Sundara Free',
			  'url' => 'https://wpkoi.com/wpkoi-elementor-templates-demo/sundara-free/',
			),
			108 => array (
			  'template_id' => 'manas-free',
			  'thumbnail' => 'manas-free-thumb.jpg',
			  'title' => 'Manas Free',
			  'url' => 'https://wpkoi.com/wpkoi-elementor-templates-demo/manas-free/',
			),
			109 => array (
			  'template_id' => 'prakasa-free',
			  'thumbnail' => 'prakasa-free-thumb.jpg',
			  'title' => 'Prakasa Free',
			  'url' => 'https://wpkoi.com/wpkoi-elementor-templates-demo/prakasa-free/',
			),
			110 => array (
			  'template_id' => 'gotra-free',
			  'thumbnail' => 'gotra-free-thumb.jpg',
			  'title' => 'Gotra Free',
			  'url' => 'https://wpkoi.com/wpkoi-elementor-templates-demo/gotra-free/',
			),
			111 => array (
			  'template_id' => 'makara-free',
			  'thumbnail' => 'makara-free-thumb.jpg',
			  'title' => 'Makara Free',
			  'url' => 'https://wpkoi.com/wpkoi-elementor-templates-demo/makara-free/',
			),
		);
		
		return $templates;
		
	}
}
